ignore:
  - benchmarks
  - data
  - developments

coverage:
  status:
    project:
      default:
        target: auto
	base: auto
  notify:
    gitter:
      default:
        url: https://webhooks.gitter.im/e/96584a4ebaea0c936db7
        threshold: 1%
