version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

build:
  image: latest

conda:
  environment: docs/conda.yml

python:
  version: 3.7
  system_packages: true
  #install:
  #  - requirements: docs/requirements.txt
  #  - method: setuptools
  #    path: .

formats:
  - htmlzip
