version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

build:
  image: latest

python:
  version: 3
  system_packages: true
  install:
    - requirements: docs/requirements.txt

formats:
  - htmlzip
