name: sisl-docs

channels:
  - conda-forge

dependencies:
  - libgcc
  - libgfortran
  - fortran-compiler
  - liblapack
  - python
  - setuptools
  - pyparsing>=1.5.7
  - numpy
  - cython
  - scipy
  - netCDF4
  - tqdm
  - matplotlib
  - numpydoc
#  - jinja2
#  - tornado
#  - nbformat
#  - jupyter_client
  - ipykernel
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  - pip
  - pip:
    # editable installation
    - -e ..
