name: sisl_docs

channels:
  - conda-forge

dependencies:
  - python=3.7
  - pyparsing
  - numpy
  - scipy
  - netCDF4
  - matplotlib
  - sphinx_rtd_theme
  - numpydoc
#  - jinja2
#  - tornado
#  - nbformat
#  - jupyter_client
#  - ipykernel
  - sphinx
#  - pip:
#    - nbsphinx
