name: sisl_docs

channels:
  - conda-forge

dependencies:
  - python
  - setuptools
  - pyparsing>=1.5.7
  - numpy
  - cython
  - scipy
  - netCDF4
  - matplotlib
  - sphinx_rtd_theme
  - numpydoc
#  - jinja2
#  - tornado
#  - nbformat
#  - jupyter_client
  - ipykernel
  - sphinx
  - pip:
    - nbsphinx
